/*
 * Minimal ODBC 3.x ABI used only by the native integration test build.
 * Windows production builds always use Microsoft's sql.h/sqlext.h/sqlucode.h.
 */
#ifndef CUBESQL_ODBC_COMPAT_H
#define CUBESQL_ODBC_COMPAT_H

#include <stddef.h>
#include <stdint.h>

#define SQL_API
typedef unsigned char SQLCHAR;
typedef uint16_t SQLWCHAR;
typedef signed char SQLSCHAR;
typedef int16_t SQLSMALLINT;
typedef uint16_t SQLUSMALLINT;
typedef int32_t SQLINTEGER;
typedef uint32_t SQLUINTEGER;
typedef intptr_t SQLLEN;
typedef uintptr_t SQLULEN;
typedef SQLSMALLINT SQLRETURN;
typedef void *SQLPOINTER;
typedef void *SQLHANDLE;
typedef SQLHANDLE SQLHENV;
typedef SQLHANDLE SQLHDBC;
typedef SQLHANDLE SQLHSTMT;
typedef SQLHANDLE SQLHDESC;
typedef void *SQLHWND;
typedef double SQLDOUBLE;
typedef float SQLREAL;
typedef uint16_t SQLSETPOSIROW;

typedef struct { SQLSMALLINT year; SQLUSMALLINT month, day; } SQL_DATE_STRUCT;
typedef struct { SQLUSMALLINT hour, minute, second; } SQL_TIME_STRUCT;
typedef struct {
    SQLSMALLINT year; SQLUSMALLINT month, day, hour, minute, second;
    SQLUINTEGER fraction;
} SQL_TIMESTAMP_STRUCT;

#define SQL_SUCCESS 0
#define SQL_SUCCESS_WITH_INFO 1
#define SQL_STILL_EXECUTING 2
#define SQL_ERROR (-1)
#define SQL_INVALID_HANDLE (-2)
#define SQL_NEED_DATA 99
#define SQL_NO_DATA 100
#define SQL_SUCCEEDED(rc) (((rc) & ~1) == 0)
#define SQL_NTS (-3)
#define SQL_NULL_DATA (-1)
#define SQL_FALSE 0
#define SQL_TRUE 1
#define SQL_DATA_AT_EXEC (-2)
#define SQL_LEN_DATA_AT_EXEC_OFFSET (-100)
#define SQL_LEN_DATA_AT_EXEC(length) (-(length) + SQL_LEN_DATA_AT_EXEC_OFFSET)

#define SQL_NULL_HANDLE NULL
#define SQL_NULL_HENV NULL
#define SQL_NULL_HDBC NULL
#define SQL_NULL_HSTMT NULL
#define SQL_NULL_HDESC NULL
#define SQL_HANDLE_ENV 1
#define SQL_HANDLE_DBC 2
#define SQL_HANDLE_STMT 3
#define SQL_HANDLE_DESC 4

#define SQL_OV_ODBC2 2
#define SQL_OV_ODBC3 3
#define SQL_OV_ODBC3_80 380
#define SQL_ATTR_ODBC_VERSION 200
#define SQL_ATTR_OUTPUT_NTS 10001

#define SQL_CLOSE 0
#define SQL_DROP 1
#define SQL_UNBIND 2
#define SQL_RESET_PARAMS 3
#define SQL_COMMIT 0
#define SQL_ROLLBACK 1

#define SQL_CHAR 1
#define SQL_NUMERIC 2
#define SQL_DECIMAL 3
#define SQL_INTEGER 4
#define SQL_SMALLINT 5
#define SQL_FLOAT 6
#define SQL_REAL 7
#define SQL_DOUBLE 8
#define SQL_VARCHAR 12
#define SQL_LONGVARCHAR (-1)
#define SQL_BINARY (-2)
#define SQL_VARBINARY (-3)
#define SQL_LONGVARBINARY (-4)
#define SQL_BIGINT (-5)
#define SQL_TINYINT (-6)
#define SQL_BIT (-7)
#define SQL_WCHAR (-8)
#define SQL_WVARCHAR (-9)
#define SQL_WLONGVARCHAR (-10)
#define SQL_TYPE_DATE 91
#define SQL_TYPE_TIME 92
#define SQL_TYPE_TIMESTAMP 93
#define SQL_UNKNOWN_TYPE 0
#define SQL_ALL_TYPES 0

#define SQL_C_CHAR SQL_CHAR
#define SQL_C_LONG SQL_INTEGER
#define SQL_C_SHORT SQL_SMALLINT
#define SQL_C_FLOAT SQL_REAL
#define SQL_C_DOUBLE SQL_DOUBLE
#define SQL_C_DEFAULT 99
#define SQL_C_TYPE_DATE SQL_TYPE_DATE
#define SQL_C_TYPE_TIME SQL_TYPE_TIME
#define SQL_C_TYPE_TIMESTAMP SQL_TYPE_TIMESTAMP
#define SQL_C_BINARY SQL_BINARY
#define SQL_C_BIT SQL_BIT
#define SQL_SIGNED_OFFSET (-20)
#define SQL_UNSIGNED_OFFSET (-22)
#define SQL_C_SBIGINT (SQL_BIGINT + SQL_SIGNED_OFFSET)
#define SQL_C_UBIGINT (SQL_BIGINT + SQL_UNSIGNED_OFFSET)
#define SQL_C_SLONG (SQL_C_LONG + SQL_SIGNED_OFFSET)
#define SQL_C_ULONG (SQL_C_LONG + SQL_UNSIGNED_OFFSET)
#define SQL_C_SSHORT (SQL_C_SHORT + SQL_SIGNED_OFFSET)
#define SQL_C_USHORT (SQL_C_SHORT + SQL_UNSIGNED_OFFSET)
#define SQL_C_STINYINT (SQL_TINYINT + SQL_SIGNED_OFFSET)
#define SQL_C_UTINYINT (SQL_TINYINT + SQL_UNSIGNED_OFFSET)
#define SQL_C_WCHAR SQL_WCHAR

#define SQL_PARAM_INPUT 1
#define SQL_PARAM_INPUT_OUTPUT 2
#define SQL_PARAM_OUTPUT 4
#define SQL_NULLABLE 1
#define SQL_NULLABLE_UNKNOWN 2
#define SQL_NO_NULLS 0
#define SQL_PARAM_SUCCESS 0
#define SQL_PARAM_SUCCESS_WITH_INFO 6
#define SQL_PARAM_ERROR 5
#define SQL_PARAM_UNUSED 7
#define SQL_ROW_SUCCESS 0
#define SQL_ROW_SUCCESS_WITH_INFO 6
#define SQL_ROW_ERROR 5
#define SQL_ROW_NOROW 3

#define SQL_FETCH_NEXT 1
#define SQL_FETCH_FIRST 2
#define SQL_FETCH_LAST 3
#define SQL_FETCH_PRIOR 4
#define SQL_FETCH_ABSOLUTE 5
#define SQL_FETCH_RELATIVE 6

#define SQL_ATTR_ACCESS_MODE 101
#define SQL_ATTR_AUTOCOMMIT 102
#define SQL_ATTR_LOGIN_TIMEOUT 103
#define SQL_ATTR_TRACE 104
#define SQL_ATTR_TRACEFILE 105
#define SQL_ATTR_TRANSLATE_LIB 106
#define SQL_ATTR_TRANSLATE_OPTION 107
#define SQL_ATTR_TXN_ISOLATION 108
#define SQL_ATTR_CURRENT_CATALOG 109
#define SQL_ATTR_ODBC_CURSORS 110
#define SQL_ATTR_QUIET_MODE 111
#define SQL_ATTR_PACKET_SIZE 112
#define SQL_ATTR_CONNECTION_TIMEOUT 113
#define SQL_ATTR_CONNECTION_DEAD 1209
#define SQL_MODE_READ_WRITE 0
#define SQL_MODE_READ_ONLY 1
#define SQL_AUTOCOMMIT_OFF 0
#define SQL_AUTOCOMMIT_ON 1
#define SQL_CD_TRUE 1
#define SQL_CD_FALSE 0
#define SQL_TXN_SERIALIZABLE 8

#define SQL_ATTR_QUERY_TIMEOUT 0
#define SQL_ATTR_MAX_ROWS 1
#define SQL_ATTR_NOSCAN 2
#define SQL_ATTR_MAX_LENGTH 3
#define SQL_ATTR_ASYNC_ENABLE 4
#define SQL_ATTR_ROW_BIND_TYPE 5
#define SQL_ATTR_CURSOR_TYPE 6
#define SQL_ATTR_CONCURRENCY 7
#define SQL_ATTR_KEYSET_SIZE 8
#define SQL_ATTR_RETRIEVE_DATA 11
#define SQL_ATTR_USE_BOOKMARKS 12
#define SQL_ATTR_ROW_BIND_OFFSET_PTR 23
#define SQL_ATTR_ROW_STATUS_PTR 25
#define SQL_ATTR_ROWS_FETCHED_PTR 26
#define SQL_ATTR_ROW_ARRAY_SIZE 27
#define SQL_ATTR_PARAM_BIND_OFFSET_PTR 17
#define SQL_ATTR_PARAM_BIND_TYPE 18
#define SQL_ATTR_PARAM_OPERATION_PTR 19
#define SQL_ATTR_PARAM_STATUS_PTR 20
#define SQL_ATTR_PARAMS_PROCESSED_PTR 21
#define SQL_ATTR_PARAMSET_SIZE 22
#define SQL_BIND_BY_COLUMN 0
#define SQL_CURSOR_FORWARD_ONLY 0
#define SQL_CURSOR_STATIC 3
#define SQL_CONCUR_READ_ONLY 1
#define SQL_RD_ON 1
#define SQL_UB_OFF 0

#define SQL_DESC_COUNT 1001
#define SQL_DESC_TYPE 1002
#define SQL_DESC_LENGTH 1003
#define SQL_DESC_PRECISION 1005
#define SQL_DESC_SCALE 1006
#define SQL_DESC_NULLABLE 1008
#define SQL_DESC_NAME 1011
#define SQL_DESC_OCTET_LENGTH 1013
#define SQL_DESC_AUTO_UNIQUE_VALUE 11
#define SQL_DESC_BASE_COLUMN_NAME 22
#define SQL_DESC_BASE_TABLE_NAME 23
#define SQL_DESC_CASE_SENSITIVE 12
#define SQL_DESC_CATALOG_NAME 17
#define SQL_DESC_CONCISE_TYPE 2
#define SQL_DESC_DISPLAY_SIZE 6
#define SQL_DESC_FIXED_PREC_SCALE 9
#define SQL_DESC_LABEL 18
#define SQL_DESC_LOCAL_TYPE_NAME 29
#define SQL_DESC_NUM_PREC_RADIX 32
#define SQL_DESC_SCHEMA_NAME 16
#define SQL_DESC_SEARCHABLE 13
#define SQL_DESC_TYPE_NAME 14
#define SQL_DESC_TABLE_NAME 15
#define SQL_DESC_UNSIGNED 8
#define SQL_DESC_UPDATABLE 10
#define SQL_PRED_BASIC 2
#define SQL_ATTR_READONLY 0

#define SQL_DIAG_NUMBER 2
#define SQL_DIAG_ROW_COUNT 3
#define SQL_DIAG_SQLSTATE 4
#define SQL_DIAG_NATIVE 5
#define SQL_DIAG_MESSAGE_TEXT 6
#define SQL_DIAG_CLASS_ORIGIN 8
#define SQL_DIAG_SUBCLASS_ORIGIN 9
#define SQL_DIAG_CONNECTION_NAME 10
#define SQL_DIAG_SERVER_NAME 11

#define SQL_DRIVER_NOPROMPT 0
#define SQL_DRIVER_COMPLETE 1
#define SQL_DRIVER_PROMPT 2
#define SQL_DRIVER_COMPLETE_REQUIRED 3

#define SQL_MAX_DRIVER_CONNECTIONS 0
#define SQL_MAX_CONCURRENT_ACTIVITIES 1
#define SQL_DATA_SOURCE_NAME 2
#define SQL_DRIVER_HDBC 3
#define SQL_DRIVER_HENV 4
#define SQL_DRIVER_HSTMT 5
#define SQL_DRIVER_NAME 6
#define SQL_DRIVER_VER 7
#define SQL_ODBC_API_CONFORMANCE 9
#define SQL_ODBC_VER 10
#define SQL_DRIVER_ODBC_VER 77
#define SQL_ROW_UPDATES 11
#define SQL_ODBC_SAG_CLI_CONFORMANCE 12
#define SQL_SERVER_NAME 13
#define SQL_SEARCH_PATTERN_ESCAPE 14
#define SQL_ODBC_SQL_CONFORMANCE 15
#define SQL_DATABASE_NAME 16
#define SQL_DBMS_NAME 17
#define SQL_DBMS_VER 18
#define SQL_ACCESSIBLE_TABLES 19
#define SQL_ACCESSIBLE_PROCEDURES 20
#define SQL_PROCEDURES 21
#define SQL_CONCAT_NULL_BEHAVIOR 22
#define SQL_CURSOR_COMMIT_BEHAVIOR 23
#define SQL_CURSOR_ROLLBACK_BEHAVIOR 24
#define SQL_DATA_SOURCE_READ_ONLY 25
#define SQL_DEFAULT_TXN_ISOLATION 26
#define SQL_EXPRESSIONS_IN_ORDERBY 27
#define SQL_IDENTIFIER_CASE 28
#define SQL_IDENTIFIER_QUOTE_CHAR 29
#define SQL_MAX_COLUMN_NAME_LEN 30
#define SQL_MAX_CURSOR_NAME_LEN 31
#define SQL_MAX_SCHEMA_NAME_LEN 32
#define SQL_MAX_PROCEDURE_NAME_LEN 33
#define SQL_MAX_CATALOG_NAME_LEN 34
#define SQL_MAX_TABLE_NAME_LEN 35
#define SQL_MULT_RESULT_SETS 36
#define SQL_MULTIPLE_ACTIVE_TXN 37
#define SQL_OUTER_JOINS 38
#define SQL_SCHEMA_TERM 39
#define SQL_PROCEDURE_TERM 40
#define SQL_CATALOG_NAME_SEPARATOR 41
#define SQL_CATALOG_TERM 42
#define SQL_SCROLL_OPTIONS 44
#define SQL_TABLE_TERM 45
#define SQL_TXN_CAPABLE 46
#define SQL_USER_NAME 47
#define SQL_TXN_ISOLATION_OPTION 72
#define SQL_QUOTED_IDENTIFIER_CASE 93
#define SQL_GETDATA_EXTENSIONS 81
#define SQL_NULL_COLLATION 85
#define SQL_ALTER_TABLE 86
#define SQL_ORDER_BY_COLUMNS_IN_SELECT 90
#define SQL_SPECIAL_CHARACTERS 94
#define SQL_MAX_COLUMNS_IN_GROUP_BY 97
#define SQL_MAX_COLUMNS_IN_INDEX 98
#define SQL_MAX_COLUMNS_IN_ORDER_BY 99
#define SQL_MAX_COLUMNS_IN_SELECT 100
#define SQL_MAX_COLUMNS_IN_TABLE 101
#define SQL_MAX_INDEX_SIZE 102
#define SQL_MAX_ROW_SIZE_INCLUDES_LONG 103
#define SQL_MAX_ROW_SIZE 104
#define SQL_MAX_STATEMENT_LEN 105
#define SQL_MAX_TABLES_IN_SELECT 106
#define SQL_MAX_USER_NAME_LEN 107
#define SQL_MAX_CHAR_LITERAL_LEN 108
#define SQL_TIMEDATE_ADD_INTERVALS 109
#define SQL_TIMEDATE_DIFF_INTERVALS 110
#define SQL_NEED_LONG_DATA_LEN 111
#define SQL_MAX_BINARY_LITERAL_LEN 112
#define SQL_LIKE_ESCAPE_CLAUSE 113
#define SQL_CATALOG_LOCATION 114
#define SQL_SQL_CONFORMANCE 118
#define SQL_ASYNC_MODE 10021
#define SQL_BATCH_SUPPORT 121
#define SQL_PARAM_ARRAY_ROW_COUNTS 153
#define SQL_PARAM_ARRAY_SELECTS 154
#define SQL_DESCRIBE_PARAMETER 10002
#define SQL_CATALOG_NAME 10003
#define SQL_MAX_IDENTIFIER_LEN 10005

#define SQL_OAC_LEVEL1 1
#define SQL_OSCC_COMPLIANT 1
#define SQL_OSC_CORE 1
#define SQL_SC_SQL92_ENTRY 1
#define SQL_CB_PRESERVE 2
#define SQL_TC_ALL 2
#define SQL_IC_MIXED 4
#define SQL_IC_SENSITIVE 3
#define SQL_CL_START 1
#define SQL_NC_LOW 2
#define SQL_SO_FORWARD_ONLY 1
#define SQL_SO_STATIC 16
#define SQL_GD_ANY_COLUMN 1
#define SQL_GD_ANY_ORDER 2
#define SQL_GD_BLOCK 4
#define SQL_AM_NONE 0
#define SQL_PARC_NO_BATCH 2
#define SQL_PAS_NO_BATCH 3
#define SQL_PAS_NO_SELECT 3
#define SQL_AT_ADD_COLUMN 1
#define SQL_AT_DROP_COLUMN 2
#define SQL_CB_NULL 0

#define SQL_API_ALL_FUNCTIONS 0
#define SQL_API_ODBC3_ALL_FUNCTIONS 999
#define SQL_API_ODBC3_ALL_FUNCTIONS_SIZE 250
#define SQL_API_SQLALLOCCONNECT 1
#define SQL_API_SQLALLOCENV 2
#define SQL_API_SQLALLOCSTMT 3
#define SQL_API_SQLALLOCHANDLE 1001
#define SQL_API_SQLBINDCOL 4
#define SQL_API_SQLBINDPARAMETER 72
#define SQL_API_SQLCANCEL 5
#define SQL_API_SQLCLOSECURSOR 1003
#define SQL_API_SQLCOLATTRIBUTE 6
#define SQL_API_SQLCOLUMNS 40
#define SQL_API_SQLCONNECT 7
#define SQL_API_SQLDESCRIBECOL 8
#define SQL_API_SQLDISCONNECT 9
#define SQL_API_SQLDRIVERCONNECT 41
#define SQL_API_SQLENDTRAN 1005
#define SQL_API_SQLEXECDIRECT 11
#define SQL_API_SQLEXECUTE 12
#define SQL_API_SQLFETCH 13
#define SQL_API_SQLFETCHSCROLL 1021
#define SQL_API_SQLFREEHANDLE 1006
#define SQL_API_SQLFREESTMT 16
#define SQL_API_SQLGETCONNECTATTR 1007
#define SQL_API_SQLGETDATA 43
#define SQL_API_SQLGETDIAGFIELD 1010
#define SQL_API_SQLGETDIAGREC 1011
#define SQL_API_SQLGETENVATTR 1012
#define SQL_API_SQLGETFUNCTIONS 44
#define SQL_API_SQLGETINFO 45
#define SQL_API_SQLGETSTMTATTR 1014
#define SQL_API_SQLGETTYPEINFO 47
#define SQL_API_SQLMORERESULTS 61
#define SQL_API_SQLNATIVESQL 62
#define SQL_API_SQLNUMPARAMS 63
#define SQL_API_SQLNUMRESULTCOLS 18
#define SQL_API_SQLPARAMDATA 48
#define SQL_API_SQLPREPARE 19
#define SQL_API_SQLPRIMARYKEYS 65
#define SQL_API_SQLPUTDATA 49
#define SQL_API_SQLROWCOUNT 20
#define SQL_API_SQLSETCONNECTATTR 1016
#define SQL_API_SQLSETENVATTR 1019
#define SQL_API_SQLSETSTMTATTR 1020
#define SQL_API_SQLSPECIALCOLUMNS 52
#define SQL_API_SQLSTATISTICS 53
#define SQL_API_SQLTABLES 54
#define SQL_API_SQLTRANSACT 23
#define SQL_API_SQLFOREIGNKEYS 60
#define SQL_API_SQLDESCRIBEPARAM 58

#define SQL_SCOPE_CURROW 0
#define SQL_SCOPE_TRANSACTION 1
#define SQL_SCOPE_SESSION 2
#define SQL_PC_NOT_PSEUDO 1
#define SQL_PC_PSEUDO 2
#define SQL_BEST_ROWID 1
#define SQL_ROWVER 2
#define SQL_INDEX_UNIQUE 0
#define SQL_INDEX_ALL 1
#define SQL_TABLE_STAT 0
#define SQL_QUICK 0
#define SQL_ENSURE 1

#endif
